### ISSUE TITLE
mujoco-py 1.50.1 with gym 0.12.0 has no attribute 'load_model_from_path'

### ISSUE THREAD

**Issue by RyanRizzo96** [openai/mujoco-py#365]
Python version: 3.6.8
Mujoco-py : 1.50.1
gym: 0.12.0

I installed MuJoCo version 1.50 and mujoco-py using:

```
pip3 install -U 'mujoco-py<1.50.2,>=1.50.1'
pip3 list | ag mujoco-py 
mujoco-py                          1.50.1.68 
```

>  import gym
 import mujoco_py
 env = gym.make('InvertedPendulum-v2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/root/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/registration.py", line 171, in make
    return registry.make(id, **kwargs)
  File "/home/root/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/registration.py", line 123, in make
    env = spec.make(**kwargs)
  File "/home/root/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/registration.py", line 87, in make
    env = cls(**_kwargs)
  File "/home/root/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/mujoco/inverted_pendulum.py", line 8, in __init__
    mujoco_env.MujocoEnv.__init__(self, 'inverted_pendulum.xml', 2)
  File "/home/root/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/mujoco/mujoco_env.py", line 29, in __init__
    self.model = mujoco_py.load_model_from_path(fullpath)
AttributeError: module 'mujoco_py' has no attribute 'load_model_from_path'

I am unable to get `gym.make('InvertedPendulum-v2')` to work. 
I then installed gym 0.9.1 and the error is no longer there however I am restricted to work with v1 environments. How can I use v2 and robotics environments if they only work with versions greater than 0.91?

Any help would be greatly appreciated. Thanks in advance.

**Comment by RyanRizzo96** [comment]
Solved:

`sudo apt install -y python3-dev zlib1g-dev libjpeg-dev cmake swig python-pyglet python3-opengl libboost-all-dev libsdl2-dev     libosmesa6-dev patchelf ffmpeg xvfb`
`pip install 'gym[all]'`
`export LD_LIBRARY_PATH=/home/root/.mujoco/mjpro150/bin`
